import * as fs from "node:fs";
import * as YAML from "yaml";

export class YamlFile {
	/**
	 * The path to the file that the object will be written to.
	 */
	private readonly filePath: string;

	private obj: Record<string, unknown>;

	constructor(filePath: string, obj: Record<string, unknown>) {
		this.filePath = filePath;
		this.obj = obj;
	}

	public toYaml(): string {
		const yamlDoc = new YAML.Document(this.obj);
		const genFilename = process.argv[1].split("/").pop();
		yamlDoc.commentBefore = `Generated by github-actions-cdk. To modify, edit ${genFilename} and run "ts-node ${genFilename}"`;

		return yamlDoc.toString({
			commentString: this.formatComment,
			indent: 2,
		});
	}

	public writeFile(): void {
		fs.writeFileSync(this.filePath, this.toYaml(), { encoding: "utf8" });
	}

	private formatComment(comment: string): string {
		return comment
			.split("\n")
			.map((line) => (line ? `# ${line}` : ""))
			.join("\n");
	}
}
